title:            Laura Barber
subtitle:         Software Engineering Blog
description:      A blog for CSCI 462 assignments.
url:              # Site url.
signoff: Laura Barber          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    icon:         fa-home
    url:          /
  - name:         About
    icon:         fa-user
    url:          /about
  - name:         Email
    icon:         fa-envelope
    url:          mailto:laura.c.barber@gmail.com
    external:     true
  - name:         Twitter
    icon:         fa-twitter
    url:          http://twitter.com/Lixxia
    external:     true
  - name:         LinkedIn
    icon:         fa-linkedin
    url:          http://linkedin.com/in/lixxia
    external:     true
  - name:         GitHub
    icon:         fa-github-alt
    url:          http://github.com/Lixxia
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
