title:            SOFTWARE ENGINEERING
description:      A blog for CSCI 462 assignments.
url:              # Site url.
signoff: Laura Barber          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    icon:         <i class="fa fa-user"></i>
    url:          /about
  - name:         Blog
    icon:         <i class="fa fa-home"></i>
    url:          /
  - name:         Email
    icon:         <i class="fa fa-envelope"></i>
    url:          mailto:laura.c.barber@gmail.com
    external:     true
  - name:         GitHub
    icon:         <i class="fa fa-github-alt"></i>
    url:          http://github.com/Lixxia
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
